- Keepin_iOS/Keepin_iOS/Sources/Join/JoinSecondVC.swift
자꾸 빨간줄 뜨길래(근데 또 실행은 됨) import Foundation 써줬더니 빨간줄이 사라졌다.
> [fix] #42 회원가입생일-> datePicker로 변경

- Keepin_iOS/Keepin_iOS/Sources/Home/DataManager/HomeDataManager.swift
- Keepin_iOS/Keepin_iOS/Sources/Home/DataModel/HomeResponse.swift
- Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
> [feat] /random 서버연결 완료

- Keepin_iOS/Keepin_iOS/Sources/EmailLogin/EmailLoginVC.xib
> [fix] #106 로그인뷰 상단 레이아웃 다시잡음

- Keepin_iOS/Keepin_iOS/Sources/EmailLogin/DataManager/EmailLoginDataManager.swift
- Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.swift
- Keepin_iOS/Keepin_iOS/Sources/Join/DataModel/JoinRequest.swift
- Keepin_iOS/Keepin_iOS/Sources/Join/DataModel/JoinResponse.swift
아 아까 한거랑 섞였다
또다시 이슈별로 브랜치파기의 중요성을 느끼는중..
> [feat] 로그인시 홈화면으로 이름 넘김

- Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeTopCVC.swift
- Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeTopCVC.xib
- Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/DataManager/MyPageHomeDataManager.swift
- Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
다 선배들 덕분이야👍 고마워!! 진짜 오늘 많이 배워간다!!
> [fix] #99 마이페이지 상단부분 수정 완료

- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusHome/KeepinPlusVC.swift
> [fix] #137 dismisskeyboard 추가

- Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopSingleTVC.swift
- Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopSingleTVC.xib
- Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
- Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.xib
> [fix] #162 홈 autolayout 잡음

- Keepin_iOS/Keepin_iOS/Sources/Login/LoginFirstVC.swift
- Keepin_iOS/Keepin_iOS/Sources/Login/LoginFirstVC.xib
> [fix] #170 첫화면 레이아웃 완료

- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.xib
1. 키보드가 textview를 가리는 것 해결
2. 아무곳이날 눌렀을때 dismiss 되도록 함
> [#308] 키핀하기 - 키보드이슈해결

- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/SelectFriendVC.swift
- Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/DataManager/MyPageHomeDataManager.swift
> [#319] 친구선택뷰 -> 키핀하기 데이터 전달

- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/DataManager/KeepinPlusMainDataManager.swift
- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
> [#321] friendIdx 2명이상일때 안보내지던거 해결

- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
> [#317] 받은/준, 카테고리 전달

- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/DataManager/KeepinPlusMainDataManager.swift
- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
> [#324] 키핀하기 이미지 전송 여러장

- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/DataManager/KeepinPlusMainDataManager.swift
- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/SelectFriendVC.swift
- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/SelectFriendVC.xib
- Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.swift
> [#350] 키핀하기 - 새친구등록 연결

- Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.swift
- Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.xib
- Keepin_iOS/Keepin_iOS/Sources/Home/DataManager/HomeDataManager.swift
- Keepin_iOS/Keepin_iOS/Sources/Home/DataModel/HomeResponse.swift
- Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
> [#358] 홈 상단 empty view 추가

- Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.swift
- Keepin_iOS/Keepin_iOS/Sources/Home/DataManager/HomeDataManager.swift
- Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
> [#86] 홈화면 랜덤 웰컴메시지 적용

- Keepin_iOS/Keepin_iOS/Configuration/Base/BaseTBC.swift
- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
> [#76] 키핀하기뷰 다시 열때 데이터 초기화

- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/Cell/SelectFriendMessageTVC.swift
- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/SelectFriendVC.swift
- Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/DataManager/MyPageHomeDataManager.swift
> [#368] 친구검색뷰 - 전체 친구목록 보이도록

- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/SelectFriend/SelectFriendVC.swift
> [#370] 전체 친구목록에 추가되지 않는 문제 해결

- Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
> [#372] 홈 데이터 새로고침 시점 고침

- Keepin_iOS/Keepin_iOS/Sources/PresentMoa/PresentMoaHome/PresentMoaVC.swift
> [#374] 키핀하기 이후 모아보기 새로고침

- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.swift
> [#376] 키핀하기뷰 메모 입력 안했을때 안내문구 그대로 넘어가는 이슈 해결

- Keepin_iOS/Keepin_iOS/Configuration/Constants.swift
- Keepin_iOS/Keepin_iOS/SceneDelegate.swift
- Keepin_iOS/Keepin_iOS/Sources/EmailLogin/DataManager/EmailLoginDataManager.swift
- Keepin_iOS/Keepin_iOS/Sources/EmailLogin/EmailLoginVC.swift
- Keepin_iOS/Keepin_iOS/Sources/Home/Cell/HomeTopTVC.swift
- Keepin_iOS/Keepin_iOS/Sources/Home/DataManager/HomeDataManager.swift
- Keepin_iOS/Keepin_iOS/Sources/Home/HomeVC.swift
- Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageProfile/MyPageProfileVC.swift
> [#387] 자동로그인/로그아웃 구현

- Keepin_iOS/Keepin_iOS/Configuration/Base/BaseTBC.swift
- Keepin_iOS/Keepin_iOS/Sources/EmailLogin/DataManager/EmailLoginDataManager.swift
- Keepin_iOS/Keepin_iOS/Sources/EmailLogin/EmailLoginVC.swift
- Keepin_iOS/Keepin_iOS/Sources/EmailLogin/EmailLoginVC.xib
- Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/Cell/MyPageHomeFriendCVC.swift
- Keepin_iOS/Keepin_iOS/Sources/MyPage/MyPageHome/MyPageHomeVC.swift
> [#389] 로그아웃후 재로그인시 이슈 해결

- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/DataManager/KeepinPlusMainDataManager.swift
> [#391] 키핀 안올라오는 문제 해결

- Keepin_iOS/Keepin_iOS/Sources/Join/JoinFirstVC.swift
- Keepin_iOS/Keepin_iOS/Sources/Join/JoinFirstVC.xib
- Keepin_iOS/Keepin_iOS/Sources/Join/JoinSecondVC.swift
- Keepin_iOS/Keepin_iOS/Sources/Join/JoinSecondVC.xib
- Keepin_iOS/Keepin_iOS/Sources/KeepinPlus/KeepinPlusMain/KeepinPlusMainVC.xib
> [#398] textfield 오토커렉션 해제
